version: '3'

tasks:
  help:
    silent: true
    desc: "Show help"
    cmds:
      - |
        echo "Usage: task [task]"
        echo ""
        echo "Tasks:"
        echo "  init - Initialize a new devlocal environment"
        echo "    name=[name] - Name of the environment e.g. devlocal-mymac"
        echo "    description='[description]' - Description of the environment"
        echo "  help - Show help"

  init:
    silent: true
    desc: "Initialize a new devlocal environment"
    inputs:
      - name: name
        desc: "Name of the environment e.g. devlocal-mymac"
      - name: description
        desc: "Description of the environment"
    cmds:
      - |
        name="{{.name}}"
        description="{{.description}}"
        
        # Check if `name` is provided
        if [ -z "$name" ]; then
          echo "name is required"
          exit 1 
        fi

        # Create `name` folder as a new project
        # Throw error if folder already exists
        if [ -d "$name" ]; then
          echo "Project already exists"
          exit 1
        else
          mkdir {{.USER_WORKING_DIR}}/$name
        fi

        cp -r "{{.TASKFILE_DIR}}/boiler/." "{{.USER_WORKING_DIR}}/$name/"

